language: ruby

bundler_args: --without development

env:
  global:
    - ILL_PATRON_STATUSES=[51,37,55,31]
    - ALEPH_BASE_URL=http://aleph.library.edu
    - ALEPH_REST_URL=http://aleph.library.edu:1891/rest-dlf
    - PRIMO_BASE_URL=http://primo.library.edu
    - LOGIN_URL=https://dev.login.library.nyu.edu
    - PASSIVE_LOGIN_PATH=/login/passive
    - SSO_LOGOUT_PATH=/logout
    - NS_BX_TOKEN=NS_BX_TOKEN
    - EZBORROW_NYU_PATRON_BARCODE=12345
    - EZBORROW_NYU_LIBRARY_SYMBOL=NYU
    - EZBORROW_NS_PATRON_BARCODE=12345
    - EZBORROW_NS_LIBRARY_SYMBOL=NS

services:
  - memcached

cache: bundler

before_script:
  - mysql -e 'create database getit_test;'
  - RAILS_ENV=test bundle exec rake db:schema:load

script: "RAILS_ENV=test bundle exec rake"

rvm:
  - 2.2.5
  - 2.3.1

git:
  submodules: false

notifications:
  email:
    - lib-webservices@nyu.edu

sudo: false
